### ISSUE TITLE
Add subconcept of finding path from node to node through Lowest Common Ancestor in Trees

### ISSUE THREAD

**Issue by DeathStroke19891** [DeathStroke19891/CP_Notes#9]
Add subconcept of finding path from node to node through Lowest Common Ancestor in Trees

[Problem Link](https://codeforces.com/contest/1981/problem/C)
[Solution Link](https://codeforces.com/blog/entry/129848)

**Comment by KTS-o7** [comment]
#20  Is added. Can close this issue
